### ISSUE TITLE
Please add possibility to remove animation

### ISSUE THREAD

**Issue by rinaldus** [ArndtB/WoW-Addon-Updater#1]
Your program is excellent! It's unique program which works properly with Curse.com addons in Linux. But can you do one thing in your next release? Can you add possibilty (in settings) to remove animation when update addons or exit program? It's slightly annoying.

**Comment by ArndtB** [comment]
Sorry for my late response, but at first: Thank you for your feedback! I'm happy that you like my program. I will implement your requested feature for next release. But this can take some time, because I'm very busy at the moment with a lot of work and family things. But I noted it and will not forget. ;-)

**Comment by ArndtB** [comment]
Fixed with 1.2.0 today.
