### ISSUE TITLE
Crash after reinstall of OS

### ISSUE THREAD

**Issue by thom-github** [ArndtB/WoW-Addon-Updater#3]
I had to reinstall my OS (Ubuntu Gnome 16.04) and, as always, I left my /home untouched, including the WAU stuff. I just installed WAU as the deb-package (no errors at all). I can start it just fine, and the list of addons is still there. But the software crashes when I click "Prüfen" to check for new addon versions.

Here's what I get from the console:

`TApplication.HandleException Access violation
  Stack trace:
  $00007F43F1CBF984
**
GLib-GObject:ERROR:/build/glib2.0-prJhLS/glib2.0-2.48.2/./gobject/gsignal.c:813:emission_pop: code should not be reached
Aborted (core dumped)
`

Any ideas how to fix this, or what information to give you?

**Comment by ArndtB** [comment]
Thank you for submitting this problem, I've checked it in a fresh Ubuntu 16.04 VM and cannot reproduce it for now. Please take a look in the **Activity log** (Info-Button, Tab "Activity Log"). Here you can find the Addon, which was involved in last procedure before crash. Please find my attached screenshot as example. 

![bildschirmfoto 2017-07-31 um 19 43 23](https://user-images.githubusercontent.com/17092004/28790936-11488d66-762b-11e7-9cb2-fc5eff4f8241.png)

Sometimes I've seen crashes, when Addon-Entries are missing and/or URLs don't exist anymore. I've implemented routines to resolve that, but sometimes the application crashes - I will investigate it in the future and try to fix it. 

When you find the erroneous Addon entry, try to uncheck it in the list and start the process again. Unselected (switched off) items will not be checked or updated. For example, ElvUI currently produce some errors with WoW-Addon-Updater, because the Developer rebuild their website now, the old URLs doesn't exist anymore. I will fix that in code in the future, when the ElvUI-Website will be finalized.

Please give me a short feedback, when you find out the erroneous Addon-Entries.

**Comment by thom-github** [comment]
Salue Arndt,

ich hab im Forum von Ubuntuusers noch n bischen mehr geschrieben
https://forum.ubuntuusers.de/topic/vorstellung-wow-addon-updater/2/

Selbst nach verschieben des .config Verzeichnisses und Angabe einer
einzigen URL (nicht ElvUI) stürzt er beim Prüfen oder Aktualisieren ab,
ohne was ins Log zu schreiben.

Gruß

**Comment by ArndtB** [comment]
Problem will be solved after installation of package **libssl-dev**, which is required for network functionality. It can be installed with `apt install libssl-dev` on Debian-based systems. I will add an dependency in Deb-Package with next release.
