### ISSUE TITLE
Exiting the setup routine is literally impossible (without going through it or killing the process)

### ISSUE THREAD

**Issue by SacredDuckwhale** [ArndtB/WoW-Addon-Updater#4]
**Steps to reproduce:**
1. Download release version (for Windows, in my case)
2. Open the program (will start the setup/initial configuration)
3. Attempt to close the program without selecting anything ('X' button, for example, but also applies to the "Cancel" button)

**What actually happens:**
An infinite loop of the three dialogues windows, prompting me to select a folder again and again (even if one has been selected in another instance of the program).

**What is expected:**
After closing any of the dialogues, the program should exit and not keep pestering the user.

**How this could happen in the first place:**
I only noticed this because I opened the download from a ZIP and it didn't display text properly, so I wanted to exit the program and extract the folder before starting it again.
It's also a problem if you open multiple instances (say, by accidentally clicking twice on the program's icon instead of just once), as it is impossible to simply close the second instance unless you go through the setup process again (or kill the program manually).

**Comment by ArndtB** [comment]
Hello & thank you for your detailed issue report. 

I understand your point, but all Addon-based functions like install and update require a valid Addon path on system. Thats the reason, the selection is absolute necessary. To solve your issue, simple select a directory on your system - after first start you can close the program and start it again from different location. You can change the Addon-path after next start. 
I'm think about other solutions, e.g. define of a "default-directory", but this will produce other errors, because WoW-Addon-Updater is platform-independend (Windows/Linux/macOS) and -additional- the user can forget to set the Addon-Directory after start. 

I apologize for the inconvenience and thank you for understanding.
